[PI-1621]: DIGIT Code Handover | Trimmed email id while create and update in PGR | Contribution By Punjab
egovernments/municipal-services pull request #862
Opened 2021-06-18 10:51 UTC by Iffath-eGov

2021-07-02 04:45 UTC, kavi-egov requested changes

2021-07-02 04:45 UTC, kavi-egov commented on rainmaker-pgr/src/main/java/org/egov/pgr/validator/PGRRequestValidator.java
> +		if(serviceRequest.getServices().get(0).getCitizen().getEmailId() !=null)
Please store it in a variable and use.

2021-07-12 12:44 UTC, Iffath-eGov commented on rainmaker-pgr/src/main/java/org/egov/pgr/validator/PGRRequestValidator.java
> +		if(serviceRequest.getServices().get(0).getCitizen().getEmailId() !=null)
Changes are done and committed

2021-07-14 09:26 UTC, kavi-egov approved these changes

2021-07-14 09:26 UTC, merged