[Rain 2895] Enhanced inbox service for PT inbox and added support for multiple creationReason search in property-services
egovernments/municipal-services pull request #868
Opened 2021-06-25 11:35 UTC by shashwat-egov

2021-06-28 09:21 UTC, kavi-egov approved these changes

2021-06-29 10:07 UTC, phanikiran-wtt-egov approved these changes

2021-06-29 12:12 UTC, talele08 requested changes

2021-06-29 12:12 UTC, talele08 commented on property-services/src/main/java/org/egov/pt/validator/PropertyValidator.java
> +		if(configs.getIsInboxSearchAllowed()){
if validation has to be by passed call the function in if statement

2021-06-29 12:12 UTC, talele08 commented on property-services/src/main/resources/application.properties
> +property.es.index=pt-fuzzy-search
index name is updated to property-services in develop branch use that instead

2021-06-30 07:31 UTC, talele08 approved these changes

2021-06-30 07:31 UTC, merged